const BLOCK_GEN_SPEED = 10000;
const BLOCK_CHECK_INTERVAL = 10;
const BLOCK_INIT_DIFFICULTY = 20;
const TOP_BLOCK = "_top_block";

module.exports = {
    BLOCK_INIT_DIFFICULTY,
    BLOCK_CHECK_INTERVAL,
    BLOCK_GEN_SPEED,
    TOP_BLOCK
}